import { StaticParamList } from '@react-navigation/native';
import { createStackNavigator, StackNavigationProp } from '@react-navigation/stack';
import {
  AccountAddScreen,
  AccountEditScreen,
  AccountSelectScreen,
  AccountsLoadingScreen,
  CategoriesScreen,
  CategoryActionsScreen,
  CategoryAddScreen,
  CategoryDeleteScreen,
  CategoryEditScreen,
  CategoryScreen,
  ContributionAddScreen,
  ContributionEditScreen,
  ContributionScreen,
  ContributionsScreen,
  ExternalAccountScreen,
  ExternalAccountsScreen,
  GoalActionsScreen,
  GoalAddScreen,
  GoalDeleteScreen,
  GoalEditScreen,
  GoalScreen,
  InvitationAddScreen,
  InvitationScreen,
  InvitationsScreen,
  MemberEditScreen,
  MemberScreen,
  MembersScreen,
  MerchantAddScreen,
  MerchantEditScreen,
  MerchantScreen,
  MerchantsScreen,
  NotificationsScreen,
  PrivacyPolicyScreen,
  RegistrationScreen,
  SendOtpScreen,
  SubscriptionActionsScreen,
  SubscriptionAddScreen,
  SubscriptionDeleteScreen,
  SubscriptionEditScreen,
  SubscriptionScreen,
  TagActionsScreen,
  TagAddScreen,
  TagDeleteScreen,
  TagEditScreen,
  TagScreen,
  TagsScreen,
  TermsAndConditionsScreen,
  TransactionActionsScreen,
  TransactionAddScreen,
  TransactionDeleteScreen,
  TransactionEditScreen,
  TransactionScreen,
  VerifyOtpScreen,
  WelcomeScreen,
} from '@screens';
import { View } from 'react-native';

import { useIsAccountSelected, useIsLoggedIn, useIsLoggedOut } from '../../hooks';
import { RootLayout } from '../../layouts';
import { bottomSheetOptions, hiddenOptions, stackOptions } from '../../options';
import BottomTabs, { bottomTabsRoute } from '../bottomTabs';

import {
  accountAddRoute,
  accountEditRoute,
  accountRoute,
  accountSelectRoute,
  accountsLoadingRoute,
  authRoute,
  bottomSheetRoute,
  categoriesRoute,
  categoryActionsRoute,
  categoryAddRoute,
  categoryDeleteRoute,
  categoryEditRoute,
  categoryRoute,
  contributionAddRoute,
  contributionEditRoute,
  contributionRoute,
  contributionsRoute,
  externalAccountRoute,
  externalAccountsRoute,
  goalActionsRoute,
  goalAddRoute,
  goalDeleteRoute,
  goalEditRoute,
  goalRoute,
  invitationAddRoute,
  invitationRoute,
  invitationsRoute,
  memberEditRoute,
  memberRoute,
  membersRoute,
  merchantAddRoute,
  merchantEditRoute,
  merchantRoute,
  merchantsRoute,
  notificationsRoute,
  openBankingRoute,
  privacyPolicyRoute,
  protectedRoute,
  publicRoute,
  registrationRoute,
  sendOtpRoute,
  subscriptionActionsRoute,
  subscriptionAddRoute,
  subscriptionDeleteRoute,
  subscriptionEditRoute,
  subscriptionRoute,
  tagActionsRoute,
  tagAddRoute,
  tagDeleteRoute,
  tagEditRoute,
  tagRoute,
  tagsRoute,
  termsAndConditionsRoute,
  transactionActionsRoute,
  transactionAddRoute,
  transactionDeleteRoute,
  transactionEditRoute,
  transactionRoute,
  verifyOtpRoute,
  welcomeRoute,
} from './types';

const RootStack = createStackNavigator({
  screenOptions: hiddenOptions,
  screenLayout: RootLayout,
  groups: {
    [authRoute]: {
      if: useIsLoggedOut,
      screenOptions: { ...stackOptions, title: '', keyboardHandlingEnabled: false },
      screens: {
        [welcomeRoute]: WelcomeScreen,
        [sendOtpRoute]: SendOtpScreen,
        [verifyOtpRoute]: VerifyOtpScreen,
        [registrationRoute]: RegistrationScreen,
      },
    },
    [protectedRoute]: {
      if: useIsLoggedIn,
      screenOptions: stackOptions,
      initialRouteName: accountsLoadingRoute,
      screens: {
        [accountsLoadingRoute]: AccountsLoadingScreen,
        [accountAddRoute]: AccountAddScreen,
        [accountEditRoute]: AccountEditScreen,
        [notificationsRoute]: NotificationsScreen,
      },
    },
    [accountRoute]: {
      if: useIsAccountSelected,
      screenOptions: stackOptions,
      initialRouteName: bottomTabsRoute,
      screens: {
        [bottomTabsRoute]: { screen: BottomTabs, options: hiddenOptions },
        [contributionAddRoute]: ContributionAddScreen,
        [contributionEditRoute]: ContributionEditScreen,
        [contributionRoute]: ContributionScreen,
        [contributionsRoute]: ContributionsScreen,
        [goalRoute]: GoalScreen,
        [categoriesRoute]: CategoriesScreen,
        [categoryRoute]: CategoryScreen,
        [invitationRoute]: InvitationScreen,
        [invitationsRoute]: InvitationsScreen,
        [tagsRoute]: TagsScreen,
        [memberRoute]: MemberScreen,
        [memberEditRoute]: MemberEditScreen,
        [merchantsRoute]: MerchantsScreen,
        [merchantAddRoute]: MerchantAddScreen,
        [merchantEditRoute]: MerchantEditScreen,
        [merchantRoute]: MerchantScreen,
        [externalAccountsRoute]: ExternalAccountsScreen,
        [externalAccountRoute]: ExternalAccountScreen,
        [openBankingRoute]: View,
      },
    },
    [bottomSheetRoute]: {
      screenOptions: bottomSheetOptions,
      screens: {
        [accountSelectRoute]: AccountSelectScreen,
        [membersRoute]: MembersScreen,
        [subscriptionRoute]: SubscriptionScreen,
        [invitationAddRoute]: InvitationAddScreen,

        // goals
        [goalAddRoute]: GoalAddScreen,
        [goalEditRoute]: GoalEditScreen,
        [goalDeleteRoute]: GoalDeleteScreen,
        [goalActionsRoute]: GoalActionsScreen,

        // transactions
        [transactionActionsRoute]: TransactionActionsScreen,
        [transactionRoute]: TransactionScreen,
        [transactionDeleteRoute]: TransactionDeleteScreen,
        [transactionAddRoute]: TransactionAddScreen,
        [transactionEditRoute]: TransactionEditScreen,

        // tags
        [tagAddRoute]: TagAddScreen,
        [tagEditRoute]: TagEditScreen,
        [tagRoute]: TagScreen,
        [tagActionsRoute]: TagActionsScreen,
        [tagDeleteRoute]: TagDeleteScreen,

        // categories
        [categoryActionsRoute]: CategoryActionsScreen,
        [categoryAddRoute]: CategoryAddScreen,
        [categoryEditRoute]: CategoryEditScreen,
        [categoryDeleteRoute]: CategoryDeleteScreen,

        // subscriptions
        [subscriptionAddRoute]: SubscriptionAddScreen,
        [subscriptionEditRoute]: SubscriptionEditScreen,
        [subscriptionActionsRoute]: SubscriptionActionsScreen,
        [subscriptionDeleteRoute]: SubscriptionDeleteScreen,
      },
    },
    [publicRoute]: {
      screenOptions: stackOptions,
      screens: {
        [privacyPolicyRoute]: PrivacyPolicyScreen,
        [termsAndConditionsRoute]: TermsAndConditionsScreen,
      },
    },
  },
});

export type RootParams = StaticParamList<typeof RootStack>;
export type RootNavigation = StackNavigationProp<RootParams>;

export default RootStack;
